# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HackMobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for HackMobile
 pod 'Alamofire', '4.4'	
	pod 'RxSwift', '~> 4.4'
	pod 'Eureka', '~> 4.3'
	pod 'RxCocoa', '~> 4.4'	
end
